### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by simplextech** [mjcumming/ISY994v5#2]
Do you have any further examples, usage documentation?

Get Nodes
Get Node Info (UOM, Precision, Parent, Children, Value)
Control Functions

Currently comparing with PyISY for a project and this seems very promising but early stage?

**Comment by mjcumming** [comment]
I wrote this ISY to work with MQTT and Homie.  

https://github.com/mjcumming/ISY-Homie-Bridge

The ISY994 class connects to the controller and is used to contain/manage the 4 main types of ISY nodes -> devices, programs, scenes, and variables all through a common base class.  

It does not try to recreate the folder structure on the ISY (parent/child). 

By subscribing to the controller you get all events from the ISY. 

For devices, I have created a common base class so that users do not need to know if the device is Insteon, zWave etc. ie. if you have a dimmer item, you can change it or monitor it without any knowledge of the underlying protocol or differences between protocols.

**Comment by simplextech** [comment]
> It does not try to recreate the folder structure on the ISY (parent/child).

I'm not meaning folder structure but ISY Node layout.  This is more specific to multi-node device such as Motion Sensor II and a lot of Z-Wave devices as they create a parent/child node structure.  Simple example is a Power Plug that has Energy Meter capabilities.  The parent is the plug with on/off and the child is the energy meter.

**Comment by mjcumming** [comment]
It would be useful to see what the rest api returns for that node - the device container would have to pass that information along to the device item so it could process it correctly.

**Comment by simplextech** [comment]
Here's a basic power plug with energy meter.

`<node flag="128" nodeDefId="UZW0004">
        <address>ZW021_1</address>
        <name>ZW 021 On-Off Power Switch</name>
        <family>4</family>
        <type>4.16.1.0</type>
        <enabled>true</enabled>
        <deviceClass>0</deviceClass>
        <wattage>0</wattage>
        <dcPeriod>0</dcPeriod>
        <startDelay>0</startDelay>
        <endDelay>0</endDelay>
        <pnode>ZW021_1</pnode>
        <sgid>1</sgid>
        <devtype>
            <gen>4.16.1</gen>
            <mfg>634.257.13</mfg>
            <cat>121</cat>
        </devtype>
        <ELK_ID>A03</ELK_ID>
        <property id="ST" value="0" formatted="Off" uom="78" />
    </node>
    <node flag="0" nodeDefId="UZW0005">
        <address>ZW021_143</address>
        <name>ZW 021 Energy Meter 1</name>
        <family>4</family>
        <type>4.16.1.0</type>
        <enabled>true</enabled>
        <deviceClass>0</deviceClass>
        <wattage>0</wattage>
        <dcPeriod>0</dcPeriod>
        <startDelay>0</startDelay>
        <endDelay>0</endDelay>
        <pnode>ZW021_1</pnode>
        <sgid>143</sgid>
        <devtype>
            <gen>4.16.1</gen>
            <mfg>634.257.13</mfg>
            <cat>143</cat>
        </devtype>
        <ELK_ID>A04</ELK_ID>
        <property id="ST" value="0" formatted="0.000 Watts" uom="73" prec="3" />
    </node>`

ZW021_1 is the root/parent device created which provides the on/off.  Another node ZW021_143 is created which has a "parent" of the root node.  This node provides the power information and doesn't have any controls.  

I can provide details for other devices as well (sensors, thermostat).  I wanted to start with a basic node first on how to try and integrate into the module the relationship and then extra parameters.

**Comment by mjcumming** [comment]
Looking at the formatted XML, I would do this as 2 devices. One as an On/Off switch, the second as an Energy meter. Use the base on/off device. We need to create a base energy device. Use the devtype/cat to differentiate between the two.

Thoughts?

```xml
<node flag="128" nodeDefId="UZW0004">
    <address>ZW021_1</address>
    <name>ZW 021 On-Off Power Switch</name>
    <family>4</family>
    <type>4.16.1.0</type>
    <enabled>true</enabled>
    <deviceClass>0</deviceClass>
    <wattage>0</wattage>
    <dcPeriod>0</dcPeriod>
    <startDelay>0</startDelay>
    <endDelay>0</endDelay>
    <pnode>ZW021_1</pnode>
    <sgid>1</sgid>
    <devtype>
        <gen>4.16.1</gen>
        <mfg>634.257.13</mfg>
        <cat>121</cat>
    </devtype>
    <ELK_ID>A03</ELK_ID>
    <property id="ST" value="0" formatted="Off" uom="78" />
</node>
<node flag="0" nodeDefId="UZW0005">
    <address>ZW021_143</address>
    <name>ZW 021 Energy Meter 1</name>
    <family>4</family>
    <type>4.16.1.0</type>
    <enabled>true</enabled>
    <deviceClass>0</deviceClass>
    <wattage>0</wattage>
    <dcPeriod>0</dcPeriod>
    <startDelay>0</startDelay>
    <endDelay>0</endDelay>
    <pnode>ZW021_1</pnode>
    <sgid>143</sgid>
    <devtype>
        <gen>4.16.1</gen>
        <mfg>634.257.13</mfg>
        <cat>143</cat>
    </devtype>
    <ELK_ID>A04</ELK_ID>
    <property id="ST" value="0" formatted="0.000 Watts" uom="73" prec="3" />
</node>'''

**Comment by simplextech** [comment]
Separate device was my thought as well.  I've already started on the base device for energy meters.  just not sure yet on the handling of linking them as the current code structure doesn't pull the information for the parent from the <pnode>.  I'll do some more work testing on this tonight.  I'm still going through the rest of your code trying to understand things before I go making any big changes.

I still have some questions around pulling the <property> as the current structure is around control so some work will be needed for "status only" type nodes.

**Comment by mjcumming** [comment]
I created a power device for zwave for you to try out - not tested. I used power not energy as the device measures watts not watt/hours. Change it if you want.

**Comment by simplextech** [comment]
Thanks.  I'll take a look soon.  Things are busy!
