### ISSUE TITLE
Child Device Properties

### ISSUE THREAD

**Issue by simplextech** [mjcumming/ISY994v5#3]
In adding Z-Wave devices I'm trying to determine a clean approach following your structure for adding child devices.  These are things like multisensors that support temp, humidity, luminance and power plugs supporting energy meters.

These show in the ISY generally as a child node of the parent and they have multiple properties besides a single ST which is in the 'extended' properties set for the node.  I haven't gone all the way through the existing discovery code yet but I'm not seeing if the 'properties' are being pulled as as single value or into a list or dictionary.  If can provide sample XML if needed for your ideas/thoughts on it.

**Comment by mjcumming** [comment]
Sample XML would be great. Agree, would like to keep the structure clean and determine a common method for handling "child" devices.
