### ISSUE TITLE
Getting Error 401, "Invalid response status" from ISY

### ISSUE THREAD

**Issue by roberthamilton-pm** [mjcumming/ISY994v5#9]
Hi there - I've set "Chunked encoding" to Off (and rebooted, to be certain), and I get a 401 error from the websocket request.

ISY994v5 connect successfully, I know, because it's able to pull all the nodes and the variables at startup.

Is there anything I can do to provide extra info to debug this?

Edit: looks like an authentication error - I'm investigating.

**Comment by mjcumming** [comment]
Its an error on my end, I have been moving over to the aiohttp library as I found the websocketclient library to silently drop connections and lock. I left credentials hard coded from testing.

Download the latest, 0.6.6 which should fix the error.  Sorry.

pip3 install ISY994v5==0.6.7

**Comment by roberthamilton-pm** [comment]
Yes - that's done the trick, thank you. Extra points for putting the pip3 command in there :)

**Comment by mjcumming** [comment]
great, btw, you can turn chunked back on, aiohttp deals with it with no issues.
